[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.4.2"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.29.1"

[[constraint]]
  name = "google.golang.org/protobuf"
  version = "1.24.0"

[[constraint]]
  branch = "master"
  name = "gopkg.qsoa.cloud/tracer"
