// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: qemail.proto

package emailpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveMailboxReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMailboxReq) Reset() {
	*x = ResolveMailboxReq{}
	mi := &file_qemail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMailboxReq) ProtoMessage() {}

func (x *ResolveMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMailboxReq.ProtoReflect.Descriptor instead.
func (*ResolveMailboxReq) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveMailboxReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ResolveMailboxResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     uint64                 `protobuf:"varint,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMailboxResp) Reset() {
	*x = ResolveMailboxResp{}
	mi := &file_qemail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMailboxResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMailboxResp) ProtoMessage() {}

func (x *ResolveMailboxResp) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMailboxResp.ProtoReflect.Descriptor instead.
func (*ResolveMailboxResp) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveMailboxResp) GetMailboxId() uint64 {
	if x != nil {
		return x.MailboxId
	}
	return 0
}

type SendEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     uint64                 `protobuf:"varint,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	TextBody      string                 `protobuf:"bytes,5,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,6,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	Bcc           []string               `protobuf:"bytes,8,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Headers       []*Header              `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailReq) Reset() {
	*x = SendEmailReq{}
	mi := &file_qemail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReq) ProtoMessage() {}

func (x *SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReq.ProtoReflect.Descriptor instead.
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{2}
}

func (x *SendEmailReq) GetMailboxId() uint64 {
	if x != nil {
		return x.MailboxId
	}
	return 0
}

func (x *SendEmailReq) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailReq) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *SendEmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailReq) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *SendEmailReq) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *SendEmailReq) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *SendEmailReq) GetBcc() []string {
	if x != nil {
		return x.Bcc
	}
	return nil
}

func (x *SendEmailReq) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_qemail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{3}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_qemail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SendEmailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResp) Reset() {
	*x = SendEmailResp{}
	mi := &file_qemail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResp) ProtoMessage() {}

func (x *SendEmailResp) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResp.ProtoReflect.Descriptor instead.
func (*SendEmailResp) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{5}
}

func (x *SendEmailResp) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ListMessagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     uint64                 `protobuf:"varint,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Folder        string                 `protobuf:"bytes,2,opt,name=folder,proto3" json:"folder,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesReq) Reset() {
	*x = ListMessagesReq{}
	mi := &file_qemail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReq) ProtoMessage() {}

func (x *ListMessagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReq.ProtoReflect.Descriptor instead.
func (*ListMessagesReq) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessagesReq) GetMailboxId() uint64 {
	if x != nil {
		return x.MailboxId
	}
	return 0
}

func (x *ListMessagesReq) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *ListMessagesReq) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMessagesReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMessagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageSummary      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResp) Reset() {
	*x = ListMessagesResp{}
	mi := &file_qemail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResp) ProtoMessage() {}

func (x *ListMessagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResp.ProtoReflect.Descriptor instead.
func (*ListMessagesResp) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{7}
}

func (x *ListMessagesResp) GetMessages() []*MessageSummary {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MessageSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Date          int64                  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Seen          bool                   `protobuf:"varint,5,opt,name=seen,proto3" json:"seen,omitempty"`
	Flagged       bool                   `protobuf:"varint,6,opt,name=flagged,proto3" json:"flagged,omitempty"`
	Size          uint32                 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	To            []string               `protobuf:"bytes,8,rep,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSummary) Reset() {
	*x = MessageSummary{}
	mi := &file_qemail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSummary) ProtoMessage() {}

func (x *MessageSummary) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSummary.ProtoReflect.Descriptor instead.
func (*MessageSummary) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{8}
}

func (x *MessageSummary) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MessageSummary) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageSummary) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MessageSummary) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *MessageSummary) GetSeen() bool {
	if x != nil {
		return x.Seen
	}
	return false
}

func (x *MessageSummary) GetFlagged() bool {
	if x != nil {
		return x.Flagged
	}
	return false
}

func (x *MessageSummary) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MessageSummary) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

type GetMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     uint64                 `protobuf:"varint,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Folder        string                 `protobuf:"bytes,3,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageReq) Reset() {
	*x = GetMessageReq{}
	mi := &file_qemail_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageReq) ProtoMessage() {}

func (x *GetMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageReq.ProtoReflect.Descriptor instead.
func (*GetMessageReq) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{9}
}

func (x *GetMessageReq) GetMailboxId() uint64 {
	if x != nil {
		return x.MailboxId
	}
	return 0
}

func (x *GetMessageReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetMessageReq) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type GetMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Date          int64                  `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`
	TextBody      string                 `protobuf:"bytes,6,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody      string                 `protobuf:"bytes,7,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,8,rep,name=attachments,proto3" json:"attachments,omitempty"`
	RawHeaders    string                 `protobuf:"bytes,9,opt,name=raw_headers,json=rawHeaders,proto3" json:"raw_headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResp) Reset() {
	*x = GetMessageResp{}
	mi := &file_qemail_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResp) ProtoMessage() {}

func (x *GetMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResp.ProtoReflect.Descriptor instead.
func (*GetMessageResp) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessageResp) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetMessageResp) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetMessageResp) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *GetMessageResp) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GetMessageResp) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GetMessageResp) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *GetMessageResp) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *GetMessageResp) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *GetMessageResp) GetRawHeaders() string {
	if x != nil {
		return x.RawHeaders
	}
	return ""
}

type DeleteMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     uint64                 `protobuf:"varint,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Folder        string                 `protobuf:"bytes,3,opt,name=folder,proto3" json:"folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageReq) Reset() {
	*x = DeleteMessageReq{}
	mi := &file_qemail_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageReq) ProtoMessage() {}

func (x *DeleteMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageReq.ProtoReflect.Descriptor instead.
func (*DeleteMessageReq) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessageReq) GetMailboxId() uint64 {
	if x != nil {
		return x.MailboxId
	}
	return 0
}

func (x *DeleteMessageReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DeleteMessageReq) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

type MoveMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MailboxId     uint64                 `protobuf:"varint,1,opt,name=mailbox_id,json=mailboxId,proto3" json:"mailbox_id,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ToFolder      string                 `protobuf:"bytes,3,opt,name=to_folder,json=toFolder,proto3" json:"to_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveMessageReq) Reset() {
	*x = MoveMessageReq{}
	mi := &file_qemail_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMessageReq) ProtoMessage() {}

func (x *MoveMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_qemail_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMessageReq.ProtoReflect.Descriptor instead.
func (*MoveMessageReq) Descriptor() ([]byte, []int) {
	return file_qemail_proto_rawDescGZIP(), []int{12}
}

func (x *MoveMessageReq) GetMailboxId() uint64 {
	if x != nil {
		return x.MailboxId
	}
	return 0
}

func (x *MoveMessageReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *MoveMessageReq) GetToFolder() string {
	if x != nil {
		return x.ToFolder
	}
	return ""
}

var File_qemail_proto protoreflect.FileDescriptor

const file_qemail_proto_rawDesc = "" +
	"\n" +
	"\fqemail.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x11ResolveMailboxReq\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"3\n" +
	"\x12ResolveMailboxResp\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\x04R\tmailboxId\"\x85\x02\n" +
	"\fSendEmailReq\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\x04R\tmailboxId\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\x05 \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\x06 \x01(\tR\bhtmlBody\x12-\n" +
	"\vattachments\x18\a \x03(\v2\v.AttachmentR\vattachments\x12\x10\n" +
	"\x03bcc\x18\b \x03(\tR\x03bcc\x12!\n" +
	"\aheaders\x18\t \x03(\v2\a.HeaderR\aheaders\"_\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\".\n" +
	"\rSendEmailResp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"v\n" +
	"\x0fListMessagesReq\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\x04R\tmailboxId\x12\x16\n" +
	"\x06folder\x18\x02 \x01(\tR\x06folder\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\rR\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"U\n" +
	"\x10ListMessagesResp\x12+\n" +
	"\bmessages\x18\x01 \x03(\v2\x0f.MessageSummaryR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total\"\xb6\x01\n" +
	"\x0eMessageSummary\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\x12\x12\n" +
	"\x04seen\x18\x05 \x01(\bR\x04seen\x12\x18\n" +
	"\aflagged\x18\x06 \x01(\bR\aflagged\x12\x12\n" +
	"\x04size\x18\a \x01(\rR\x04size\x12\x0e\n" +
	"\x02to\x18\b \x03(\tR\x02to\"X\n" +
	"\rGetMessageReq\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\x04R\tmailboxId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\tR\x06folder\"\xfc\x01\n" +
	"\x0eGetMessageResp\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x03 \x03(\tR\x02cc\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x12\n" +
	"\x04date\x18\x05 \x01(\x03R\x04date\x12\x1b\n" +
	"\ttext_body\x18\x06 \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\a \x01(\tR\bhtmlBody\x12-\n" +
	"\vattachments\x18\b \x03(\v2\v.AttachmentR\vattachments\x12\x1f\n" +
	"\vraw_headers\x18\t \x01(\tR\n" +
	"rawHeaders\"[\n" +
	"\x10DeleteMessageReq\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\x04R\tmailboxId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\tR\x06folder\"^\n" +
	"\x0eMoveMessageReq\x12\x1d\n" +
	"\n" +
	"mailbox_id\x18\x01 \x01(\x04R\tmailboxId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1b\n" +
	"\tto_folder\x18\x03 \x01(\tR\btoFolder2\xc7\x02\n" +
	"\x06QEmail\x129\n" +
	"\x0eResolveMailbox\x12\x12.ResolveMailboxReq\x1a\x13.ResolveMailboxResp\x12*\n" +
	"\tSendEmail\x12\r.SendEmailReq\x1a\x0e.SendEmailResp\x123\n" +
	"\fListMessages\x12\x10.ListMessagesReq\x1a\x11.ListMessagesResp\x12-\n" +
	"\n" +
	"GetMessage\x12\x0e.GetMessageReq\x1a\x0f.GetMessageResp\x12:\n" +
	"\rDeleteMessage\x12\x11.DeleteMessageReq\x1a\x16.google.protobuf.Empty\x126\n" +
	"\vMoveMessage\x12\x0f.MoveMessageReq\x1a\x16.google.protobuf.EmptyB\vZ\t.;emailpbb\x06proto3"

var (
	file_qemail_proto_rawDescOnce sync.Once
	file_qemail_proto_rawDescData []byte
)

func file_qemail_proto_rawDescGZIP() []byte {
	file_qemail_proto_rawDescOnce.Do(func() {
		file_qemail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qemail_proto_rawDesc), len(file_qemail_proto_rawDesc)))
	})
	return file_qemail_proto_rawDescData
}

var file_qemail_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_qemail_proto_goTypes = []any{
	(*ResolveMailboxReq)(nil),  // 0: ResolveMailboxReq
	(*ResolveMailboxResp)(nil), // 1: ResolveMailboxResp
	(*SendEmailReq)(nil),       // 2: SendEmailReq
	(*Attachment)(nil),         // 3: Attachment
	(*Header)(nil),             // 4: Header
	(*SendEmailResp)(nil),      // 5: SendEmailResp
	(*ListMessagesReq)(nil),    // 6: ListMessagesReq
	(*ListMessagesResp)(nil),   // 7: ListMessagesResp
	(*MessageSummary)(nil),     // 8: MessageSummary
	(*GetMessageReq)(nil),      // 9: GetMessageReq
	(*GetMessageResp)(nil),     // 10: GetMessageResp
	(*DeleteMessageReq)(nil),   // 11: DeleteMessageReq
	(*MoveMessageReq)(nil),     // 12: MoveMessageReq
	(*emptypb.Empty)(nil),      // 13: google.protobuf.Empty
}
var file_qemail_proto_depIdxs = []int32{
	3,  // 0: SendEmailReq.attachments:type_name -> Attachment
	4,  // 1: SendEmailReq.headers:type_name -> Header
	8,  // 2: ListMessagesResp.messages:type_name -> MessageSummary
	3,  // 3: GetMessageResp.attachments:type_name -> Attachment
	0,  // 4: QEmail.ResolveMailbox:input_type -> ResolveMailboxReq
	2,  // 5: QEmail.SendEmail:input_type -> SendEmailReq
	6,  // 6: QEmail.ListMessages:input_type -> ListMessagesReq
	9,  // 7: QEmail.GetMessage:input_type -> GetMessageReq
	11, // 8: QEmail.DeleteMessage:input_type -> DeleteMessageReq
	12, // 9: QEmail.MoveMessage:input_type -> MoveMessageReq
	1,  // 10: QEmail.ResolveMailbox:output_type -> ResolveMailboxResp
	5,  // 11: QEmail.SendEmail:output_type -> SendEmailResp
	7,  // 12: QEmail.ListMessages:output_type -> ListMessagesResp
	10, // 13: QEmail.GetMessage:output_type -> GetMessageResp
	13, // 14: QEmail.DeleteMessage:output_type -> google.protobuf.Empty
	13, // 15: QEmail.MoveMessage:output_type -> google.protobuf.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_qemail_proto_init() }
func file_qemail_proto_init() {
	if File_qemail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qemail_proto_rawDesc), len(file_qemail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qemail_proto_goTypes,
		DependencyIndexes: file_qemail_proto_depIdxs,
		MessageInfos:      file_qemail_proto_msgTypes,
	}.Build()
	File_qemail_proto = out.File
	file_qemail_proto_goTypes = nil
	file_qemail_proto_depIdxs = nil
}
