// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: qemail.proto

package emailpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QEmail_ResolveMailbox_FullMethodName = "/QEmail/ResolveMailbox"
	QEmail_SendEmail_FullMethodName      = "/QEmail/SendEmail"
	QEmail_ListMessages_FullMethodName   = "/QEmail/ListMessages"
	QEmail_GetMessage_FullMethodName     = "/QEmail/GetMessage"
	QEmail_DeleteMessage_FullMethodName  = "/QEmail/DeleteMessage"
	QEmail_MoveMessage_FullMethodName    = "/QEmail/MoveMessage"
)

// QEmailClient is the client API for QEmail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QEmailClient interface {
	ResolveMailbox(ctx context.Context, in *ResolveMailboxReq, opts ...grpc.CallOption) (*ResolveMailboxResp, error)
	SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailResp, error)
	ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error)
	GetMessage(ctx context.Context, in *GetMessageReq, opts ...grpc.CallOption) (*GetMessageResp, error)
	DeleteMessage(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveMessage(ctx context.Context, in *MoveMessageReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type qEmailClient struct {
	cc grpc.ClientConnInterface
}

func NewQEmailClient(cc grpc.ClientConnInterface) QEmailClient {
	return &qEmailClient{cc}
}

func (c *qEmailClient) ResolveMailbox(ctx context.Context, in *ResolveMailboxReq, opts ...grpc.CallOption) (*ResolveMailboxResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveMailboxResp)
	err := c.cc.Invoke(ctx, QEmail_ResolveMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEmailClient) SendEmail(ctx context.Context, in *SendEmailReq, opts ...grpc.CallOption) (*SendEmailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResp)
	err := c.cc.Invoke(ctx, QEmail_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEmailClient) ListMessages(ctx context.Context, in *ListMessagesReq, opts ...grpc.CallOption) (*ListMessagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMessagesResp)
	err := c.cc.Invoke(ctx, QEmail_ListMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEmailClient) GetMessage(ctx context.Context, in *GetMessageReq, opts ...grpc.CallOption) (*GetMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageResp)
	err := c.cc.Invoke(ctx, QEmail_GetMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEmailClient) DeleteMessage(ctx context.Context, in *DeleteMessageReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QEmail_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qEmailClient) MoveMessage(ctx context.Context, in *MoveMessageReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QEmail_MoveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QEmailServer is the server API for QEmail service.
// All implementations must embed UnimplementedQEmailServer
// for forward compatibility.
type QEmailServer interface {
	ResolveMailbox(context.Context, *ResolveMailboxReq) (*ResolveMailboxResp, error)
	SendEmail(context.Context, *SendEmailReq) (*SendEmailResp, error)
	ListMessages(context.Context, *ListMessagesReq) (*ListMessagesResp, error)
	GetMessage(context.Context, *GetMessageReq) (*GetMessageResp, error)
	DeleteMessage(context.Context, *DeleteMessageReq) (*emptypb.Empty, error)
	MoveMessage(context.Context, *MoveMessageReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedQEmailServer()
}

// UnimplementedQEmailServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQEmailServer struct{}

func (UnimplementedQEmailServer) ResolveMailbox(context.Context, *ResolveMailboxReq) (*ResolveMailboxResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveMailbox not implemented")
}
func (UnimplementedQEmailServer) SendEmail(context.Context, *SendEmailReq) (*SendEmailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedQEmailServer) ListMessages(context.Context, *ListMessagesReq) (*ListMessagesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMessages not implemented")
}
func (UnimplementedQEmailServer) GetMessage(context.Context, *GetMessageReq) (*GetMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedQEmailServer) DeleteMessage(context.Context, *DeleteMessageReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedQEmailServer) MoveMessage(context.Context, *MoveMessageReq) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveMessage not implemented")
}
func (UnimplementedQEmailServer) mustEmbedUnimplementedQEmailServer() {}
func (UnimplementedQEmailServer) testEmbeddedByValue()                {}

// UnsafeQEmailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QEmailServer will
// result in compilation errors.
type UnsafeQEmailServer interface {
	mustEmbedUnimplementedQEmailServer()
}

func RegisterQEmailServer(s grpc.ServiceRegistrar, srv QEmailServer) {
	// If the following call panics, it indicates UnimplementedQEmailServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QEmail_ServiceDesc, srv)
}

func _QEmail_ResolveMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveMailboxReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEmailServer).ResolveMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEmail_ResolveMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEmailServer).ResolveMailbox(ctx, req.(*ResolveMailboxReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEmail_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEmailServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEmail_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEmailServer).SendEmail(ctx, req.(*SendEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEmail_ListMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEmailServer).ListMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEmail_ListMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEmailServer).ListMessages(ctx, req.(*ListMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEmail_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEmailServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEmail_GetMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEmailServer).GetMessage(ctx, req.(*GetMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEmail_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEmailServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEmail_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEmailServer).DeleteMessage(ctx, req.(*DeleteMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _QEmail_MoveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QEmailServer).MoveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QEmail_MoveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QEmailServer).MoveMessage(ctx, req.(*MoveMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// QEmail_ServiceDesc is the grpc.ServiceDesc for QEmail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QEmail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "QEmail",
	HandlerType: (*QEmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveMailbox",
			Handler:    _QEmail_ResolveMailbox_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _QEmail_SendEmail_Handler,
		},
		{
			MethodName: "ListMessages",
			Handler:    _QEmail_ListMessages_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _QEmail_GetMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _QEmail_DeleteMessage_Handler,
		},
		{
			MethodName: "MoveMessage",
			Handler:    _QEmail_MoveMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qemail.proto",
}
