// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: dfs.proto

package dfspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileResp_Error_Type int32

const (
	FileResp_Error_OTHER          FileResp_Error_Type = 0
	FileResp_Error_EXIST          FileResp_Error_Type = 1
	FileResp_Error_NOT_EXIST      FileResp_Error_Type = 2
	FileResp_Error_EOF            FileResp_Error_Type = 3
	FileResp_Error_UNEXPECTED_EOF FileResp_Error_Type = 4
)

// Enum value maps for FileResp_Error_Type.
var (
	FileResp_Error_Type_name = map[int32]string{
		0: "OTHER",
		1: "EXIST",
		2: "NOT_EXIST",
		3: "EOF",
		4: "UNEXPECTED_EOF",
	}
	FileResp_Error_Type_value = map[string]int32{
		"OTHER":          0,
		"EXIST":          1,
		"NOT_EXIST":      2,
		"EOF":            3,
		"UNEXPECTED_EOF": 4,
	}
)

func (x FileResp_Error_Type) Enum() *FileResp_Error_Type {
	p := new(FileResp_Error_Type)
	*p = x
	return p
}

func (x FileResp_Error_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileResp_Error_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_dfs_proto_enumTypes[0].Descriptor()
}

func (FileResp_Error_Type) Type() protoreflect.EnumType {
	return &file_dfs_proto_enumTypes[0]
}

func (x FileResp_Error_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileResp_Error_Type.Descriptor instead.
func (FileResp_Error_Type) EnumDescriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 0, 0}
}

type FileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*FileReq_Open_
	//	*FileReq_Seek_
	//	*FileReq_Write_
	//	*FileReq_Read_
	//	*FileReq_Close_
	//	*FileReq_ReadDir_
	//	*FileReq_Stat_
	Msg isFileReq_Msg `protobuf_oneof:"msg"`
}

func (x *FileReq) Reset() {
	*x = FileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq) ProtoMessage() {}

func (x *FileReq) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq.ProtoReflect.Descriptor instead.
func (*FileReq) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0}
}

func (m *FileReq) GetMsg() isFileReq_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *FileReq) GetOpen() *FileReq_Open {
	if x, ok := x.GetMsg().(*FileReq_Open_); ok {
		return x.Open
	}
	return nil
}

func (x *FileReq) GetSeek() *FileReq_Seek {
	if x, ok := x.GetMsg().(*FileReq_Seek_); ok {
		return x.Seek
	}
	return nil
}

func (x *FileReq) GetWrite() *FileReq_Write {
	if x, ok := x.GetMsg().(*FileReq_Write_); ok {
		return x.Write
	}
	return nil
}

func (x *FileReq) GetRead() *FileReq_Read {
	if x, ok := x.GetMsg().(*FileReq_Read_); ok {
		return x.Read
	}
	return nil
}

func (x *FileReq) GetClose() *FileReq_Close {
	if x, ok := x.GetMsg().(*FileReq_Close_); ok {
		return x.Close
	}
	return nil
}

func (x *FileReq) GetReadDir() *FileReq_ReadDir {
	if x, ok := x.GetMsg().(*FileReq_ReadDir_); ok {
		return x.ReadDir
	}
	return nil
}

func (x *FileReq) GetStat() *FileReq_Stat {
	if x, ok := x.GetMsg().(*FileReq_Stat_); ok {
		return x.Stat
	}
	return nil
}

type isFileReq_Msg interface {
	isFileReq_Msg()
}

type FileReq_Open_ struct {
	Open *FileReq_Open `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type FileReq_Seek_ struct {
	Seek *FileReq_Seek `protobuf:"bytes,2,opt,name=seek,proto3,oneof"`
}

type FileReq_Write_ struct {
	Write *FileReq_Write `protobuf:"bytes,3,opt,name=write,proto3,oneof"`
}

type FileReq_Read_ struct {
	Read *FileReq_Read `protobuf:"bytes,4,opt,name=read,proto3,oneof"`
}

type FileReq_Close_ struct {
	Close *FileReq_Close `protobuf:"bytes,5,opt,name=close,proto3,oneof"`
}

type FileReq_ReadDir_ struct {
	ReadDir *FileReq_ReadDir `protobuf:"bytes,6,opt,name=readDir,proto3,oneof"`
}

type FileReq_Stat_ struct {
	Stat *FileReq_Stat `protobuf:"bytes,7,opt,name=stat,proto3,oneof"`
}

func (*FileReq_Open_) isFileReq_Msg() {}

func (*FileReq_Seek_) isFileReq_Msg() {}

func (*FileReq_Write_) isFileReq_Msg() {}

func (*FileReq_Read_) isFileReq_Msg() {}

func (*FileReq_Close_) isFileReq_Msg() {}

func (*FileReq_ReadDir_) isFileReq_Msg() {}

func (*FileReq_Stat_) isFileReq_Msg() {}

type FileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*FileResp_Open_
	//	*FileResp_Seek_
	//	*FileResp_Write_
	//	*FileResp_Read_
	//	*FileResp_Close_
	//	*FileResp_ReadDir_
	//	*FileResp_Stat_
	Msg isFileResp_Msg `protobuf_oneof:"msg"`
}

func (x *FileResp) Reset() {
	*x = FileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp) ProtoMessage() {}

func (x *FileResp) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp.ProtoReflect.Descriptor instead.
func (*FileResp) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1}
}

func (m *FileResp) GetMsg() isFileResp_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *FileResp) GetOpen() *FileResp_Open {
	if x, ok := x.GetMsg().(*FileResp_Open_); ok {
		return x.Open
	}
	return nil
}

func (x *FileResp) GetSeek() *FileResp_Seek {
	if x, ok := x.GetMsg().(*FileResp_Seek_); ok {
		return x.Seek
	}
	return nil
}

func (x *FileResp) GetWrite() *FileResp_Write {
	if x, ok := x.GetMsg().(*FileResp_Write_); ok {
		return x.Write
	}
	return nil
}

func (x *FileResp) GetRead() *FileResp_Read {
	if x, ok := x.GetMsg().(*FileResp_Read_); ok {
		return x.Read
	}
	return nil
}

func (x *FileResp) GetClose() *FileResp_Close {
	if x, ok := x.GetMsg().(*FileResp_Close_); ok {
		return x.Close
	}
	return nil
}

func (x *FileResp) GetReadDir() *FileResp_ReadDir {
	if x, ok := x.GetMsg().(*FileResp_ReadDir_); ok {
		return x.ReadDir
	}
	return nil
}

func (x *FileResp) GetStat() *FileResp_Stat {
	if x, ok := x.GetMsg().(*FileResp_Stat_); ok {
		return x.Stat
	}
	return nil
}

type isFileResp_Msg interface {
	isFileResp_Msg()
}

type FileResp_Open_ struct {
	Open *FileResp_Open `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type FileResp_Seek_ struct {
	Seek *FileResp_Seek `protobuf:"bytes,2,opt,name=seek,proto3,oneof"`
}

type FileResp_Write_ struct {
	Write *FileResp_Write `protobuf:"bytes,3,opt,name=write,proto3,oneof"`
}

type FileResp_Read_ struct {
	Read *FileResp_Read `protobuf:"bytes,4,opt,name=read,proto3,oneof"`
}

type FileResp_Close_ struct {
	Close *FileResp_Close `protobuf:"bytes,5,opt,name=close,proto3,oneof"`
}

type FileResp_ReadDir_ struct {
	ReadDir *FileResp_ReadDir `protobuf:"bytes,6,opt,name=readDir,proto3,oneof"`
}

type FileResp_Stat_ struct {
	Stat *FileResp_Stat `protobuf:"bytes,7,opt,name=stat,proto3,oneof"`
}

func (*FileResp_Open_) isFileResp_Msg() {}

func (*FileResp_Seek_) isFileResp_Msg() {}

func (*FileResp_Write_) isFileResp_Msg() {}

func (*FileResp_Read_) isFileResp_Msg() {}

func (*FileResp_Close_) isFileResp_Msg() {}

func (*FileResp_ReadDir_) isFileResp_Msg() {}

func (*FileResp_Stat_) isFileResp_Msg() {}

type MkDirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *MkDirReq) Reset() {
	*x = MkDirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkDirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkDirReq) ProtoMessage() {}

func (x *MkDirReq) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkDirReq.ProtoReflect.Descriptor instead.
func (*MkDirReq) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{2}
}

func (x *MkDirReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MkDirReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type RemoveAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *RemoveAllReq) Reset() {
	*x = RemoveAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllReq) ProtoMessage() {}

func (x *RemoveAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllReq.ProtoReflect.Descriptor instead.
func (*RemoveAllReq) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveAllReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RemoveAllReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type RenameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket  string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	OldName string `protobuf:"bytes,2,opt,name=oldName,proto3" json:"oldName,omitempty"`
	NewName string `protobuf:"bytes,3,opt,name=newName,proto3" json:"newName,omitempty"`
}

func (x *RenameReq) Reset() {
	*x = RenameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReq) ProtoMessage() {}

func (x *RenameReq) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReq.ProtoReflect.Descriptor instead.
func (*RenameReq) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{4}
}

func (x *RenameReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RenameReq) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameReq) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type StatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *StatReq) Reset() {
	*x = StatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReq) ProtoMessage() {}

func (x *StatReq) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReq.ProtoReflect.Descriptor instead.
func (*StatReq) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{5}
}

func (x *StatReq) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *StatReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type StatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size    int64  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTime int64  `protobuf:"varint,3,opt,name=modTime,proto3" json:"modTime,omitempty"`
	IsDir   bool   `protobuf:"varint,4,opt,name=isDir,proto3" json:"isDir,omitempty"`
}

func (x *StatResp) Reset() {
	*x = StatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResp) ProtoMessage() {}

func (x *StatResp) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResp.ProtoReflect.Descriptor instead.
func (*StatResp) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{6}
}

func (x *StatResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResp) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *StatResp) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type FileReq_Open struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket   string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Flag     int64  `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *FileReq_Open) Reset() {
	*x = FileReq_Open{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_Open) ProtoMessage() {}

func (x *FileReq_Open) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_Open.ProtoReflect.Descriptor instead.
func (*FileReq_Open) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FileReq_Open) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileReq_Open) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileReq_Open) GetFlag() int64 {
	if x != nil {
		return x.Flag
	}
	return 0
}

type FileReq_Seek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Whence int64 `protobuf:"varint,2,opt,name=whence,proto3" json:"whence,omitempty"`
}

func (x *FileReq_Seek) Reset() {
	*x = FileReq_Seek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_Seek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_Seek) ProtoMessage() {}

func (x *FileReq_Seek) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_Seek.ProtoReflect.Descriptor instead.
func (*FileReq_Seek) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FileReq_Seek) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileReq_Seek) GetWhence() int64 {
	if x != nil {
		return x.Whence
	}
	return 0
}

type FileReq_Write struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileReq_Write) Reset() {
	*x = FileReq_Write{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_Write) ProtoMessage() {}

func (x *FileReq_Write) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_Write.ProtoReflect.Descriptor instead.
func (*FileReq_Write) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 2}
}

func (x *FileReq_Write) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FileReq_Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int64 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *FileReq_Read) Reset() {
	*x = FileReq_Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_Read) ProtoMessage() {}

func (x *FileReq_Read) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_Read.ProtoReflect.Descriptor instead.
func (*FileReq_Read) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 3}
}

func (x *FileReq_Read) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

type FileReq_Close struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileReq_Close) Reset() {
	*x = FileReq_Close{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_Close) ProtoMessage() {}

func (x *FileReq_Close) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_Close.ProtoReflect.Descriptor instead.
func (*FileReq_Close) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 4}
}

type FileReq_ReadDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N int64 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
}

func (x *FileReq_ReadDir) Reset() {
	*x = FileReq_ReadDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_ReadDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_ReadDir) ProtoMessage() {}

func (x *FileReq_ReadDir) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_ReadDir.ProtoReflect.Descriptor instead.
func (*FileReq_ReadDir) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 5}
}

func (x *FileReq_ReadDir) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

type FileReq_Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FileReq_Stat) Reset() {
	*x = FileReq_Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq_Stat) ProtoMessage() {}

func (x *FileReq_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq_Stat.ProtoReflect.Descriptor instead.
func (*FileReq_Stat) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{0, 6}
}

type FileResp_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type FileResp_Error_Type `protobuf:"varint,1,opt,name=type,proto3,enum=FileResp_Error_Type" json:"type,omitempty"`
	Msg  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FileResp_Error) Reset() {
	*x = FileResp_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Error) ProtoMessage() {}

func (x *FileResp_Error) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Error.ProtoReflect.Descriptor instead.
func (*FileResp_Error) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FileResp_Error) GetType() FileResp_Error_Type {
	if x != nil {
		return x.Type
	}
	return FileResp_Error_OTHER
}

func (x *FileResp_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FileResp_Open struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *FileResp_Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_Open) Reset() {
	*x = FileResp_Open{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Open) ProtoMessage() {}

func (x *FileResp_Open) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Open.ProtoReflect.Descriptor instead.
func (*FileResp_Open) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 1}
}

func (x *FileResp_Open) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileResp_Seek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N     int64           `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Error *FileResp_Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_Seek) Reset() {
	*x = FileResp_Seek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Seek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Seek) ProtoMessage() {}

func (x *FileResp_Seek) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Seek.ProtoReflect.Descriptor instead.
func (*FileResp_Seek) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 2}
}

func (x *FileResp_Seek) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *FileResp_Seek) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileResp_Write struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N     int64           `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	Error *FileResp_Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_Write) Reset() {
	*x = FileResp_Write{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Write) ProtoMessage() {}

func (x *FileResp_Write) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Write.ProtoReflect.Descriptor instead.
func (*FileResp_Write) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 3}
}

func (x *FileResp_Write) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *FileResp_Write) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileResp_Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []byte          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error *FileResp_Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_Read) Reset() {
	*x = FileResp_Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Read) ProtoMessage() {}

func (x *FileResp_Read) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Read.ProtoReflect.Descriptor instead.
func (*FileResp_Read) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 4}
}

func (x *FileResp_Read) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FileResp_Read) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileResp_Close struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *FileResp_Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_Close) Reset() {
	*x = FileResp_Close{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Close) ProtoMessage() {}

func (x *FileResp_Close) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Close.ProtoReflect.Descriptor instead.
func (*FileResp_Close) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 5}
}

func (x *FileResp_Close) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileResp_ReadDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*StatResp     `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Error *FileResp_Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_ReadDir) Reset() {
	*x = FileResp_ReadDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_ReadDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_ReadDir) ProtoMessage() {}

func (x *FileResp_ReadDir) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_ReadDir.ProtoReflect.Descriptor instead.
func (*FileResp_ReadDir) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 6}
}

func (x *FileResp_ReadDir) GetFiles() []*StatResp {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileResp_ReadDir) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type FileResp_Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File  *StatResp       `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Error *FileResp_Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResp_Stat) Reset() {
	*x = FileResp_Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResp_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp_Stat) ProtoMessage() {}

func (x *FileResp_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_dfs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp_Stat.ProtoReflect.Descriptor instead.
func (*FileResp_Stat) Descriptor() ([]byte, []int) {
	return file_dfs_proto_rawDescGZIP(), []int{1, 7}
}

func (x *FileResp_Stat) GetFile() *StatResp {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileResp_Stat) GetError() *FileResp_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_dfs_proto protoreflect.FileDescriptor

var file_dfs_proto_rawDesc = []byte{
	0x0a, 0x09, 0x64, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x04, 0x0a, 0x07, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x48, 0x00, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x65, 0x65,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x2e, 0x53, 0x65, 0x65, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x65, 0x6b, 0x12, 0x26,
	0x0a, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x44, 0x69,
	0x72, 0x12, 0x23, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x48, 0x00,
	0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x1a, 0x4e, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x1a, 0x36, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x68, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x68, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0x1b,
	0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x0a, 0x04, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01,
	0x6e, 0x1a, 0x07, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x1a, 0x17, 0x0a, 0x07, 0x52, 0x65,
	0x61, 0x64, 0x44, 0x69, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x01, 0x6e, 0x1a, 0x06, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0xf8, 0x06, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x24, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x48, 0x00, 0x52,
	0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x53,
	0x65, 0x65, 0x6b, 0x48, 0x00, 0x52, 0x04, 0x73, 0x65, 0x65, 0x6b, 0x12, 0x27, 0x0a, 0x05, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72, 0x48, 0x00, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x44,
	0x69, 0x72, 0x12, 0x24, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x1a, 0x8d, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x14, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x48,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x45,
	0x4f, 0x46, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x45, 0x58, 0x50, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x5f, 0x45, 0x4f, 0x46, 0x10, 0x04, 0x1a, 0x2d, 0x0a, 0x04, 0x4f, 0x70, 0x65, 0x6e,
	0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x3b, 0x0a, 0x04, 0x53, 0x65, 0x65, 0x6b, 0x12,
	0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x25, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x1a, 0x3c, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6e, 0x12, 0x25, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x1a, 0x41, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x25,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x2e, 0x0a, 0x05, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x51, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x44, 0x69, 0x72,
	0x12, 0x1f, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x4c, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x1d, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3e, 0x0a,
	0x08, 0x4d, 0x6b, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a,
	0x0c, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x57, 0x0a, 0x09, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x6c, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x07, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a, 0x08, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x6d, 0x6f, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x44, 0x69, 0x72, 0x32, 0xd1, 0x01,
	0x0a, 0x03, 0x44, 0x66, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x08, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x28, 0x01, 0x30, 0x01, 0x12, 0x2a, 0x0a, 0x05, 0x4d, 0x6b, 0x44, 0x69, 0x72, 0x12,
	0x09, 0x2e, 0x4d, 0x6b, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x32, 0x0a, 0x09, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x12,
	0x0d, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x0a, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x08, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x64, 0x66, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dfs_proto_rawDescOnce sync.Once
	file_dfs_proto_rawDescData = file_dfs_proto_rawDesc
)

func file_dfs_proto_rawDescGZIP() []byte {
	file_dfs_proto_rawDescOnce.Do(func() {
		file_dfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_dfs_proto_rawDescData)
	})
	return file_dfs_proto_rawDescData
}

var file_dfs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dfs_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_dfs_proto_goTypes = []interface{}{
	(FileResp_Error_Type)(0), // 0: FileResp.Error.Type
	(*FileReq)(nil),          // 1: FileReq
	(*FileResp)(nil),         // 2: FileResp
	(*MkDirReq)(nil),         // 3: MkDirReq
	(*RemoveAllReq)(nil),     // 4: RemoveAllReq
	(*RenameReq)(nil),        // 5: RenameReq
	(*StatReq)(nil),          // 6: StatReq
	(*StatResp)(nil),         // 7: StatResp
	(*FileReq_Open)(nil),     // 8: FileReq.Open
	(*FileReq_Seek)(nil),     // 9: FileReq.Seek
	(*FileReq_Write)(nil),    // 10: FileReq.Write
	(*FileReq_Read)(nil),     // 11: FileReq.Read
	(*FileReq_Close)(nil),    // 12: FileReq.Close
	(*FileReq_ReadDir)(nil),  // 13: FileReq.ReadDir
	(*FileReq_Stat)(nil),     // 14: FileReq.Stat
	(*FileResp_Error)(nil),   // 15: FileResp.Error
	(*FileResp_Open)(nil),    // 16: FileResp.Open
	(*FileResp_Seek)(nil),    // 17: FileResp.Seek
	(*FileResp_Write)(nil),   // 18: FileResp.Write
	(*FileResp_Read)(nil),    // 19: FileResp.Read
	(*FileResp_Close)(nil),   // 20: FileResp.Close
	(*FileResp_ReadDir)(nil), // 21: FileResp.ReadDir
	(*FileResp_Stat)(nil),    // 22: FileResp.Stat
	(*emptypb.Empty)(nil),    // 23: google.protobuf.Empty
}
var file_dfs_proto_depIdxs = []int32{
	8,  // 0: FileReq.open:type_name -> FileReq.Open
	9,  // 1: FileReq.seek:type_name -> FileReq.Seek
	10, // 2: FileReq.write:type_name -> FileReq.Write
	11, // 3: FileReq.read:type_name -> FileReq.Read
	12, // 4: FileReq.close:type_name -> FileReq.Close
	13, // 5: FileReq.readDir:type_name -> FileReq.ReadDir
	14, // 6: FileReq.stat:type_name -> FileReq.Stat
	16, // 7: FileResp.open:type_name -> FileResp.Open
	17, // 8: FileResp.seek:type_name -> FileResp.Seek
	18, // 9: FileResp.write:type_name -> FileResp.Write
	19, // 10: FileResp.read:type_name -> FileResp.Read
	20, // 11: FileResp.close:type_name -> FileResp.Close
	21, // 12: FileResp.readDir:type_name -> FileResp.ReadDir
	22, // 13: FileResp.stat:type_name -> FileResp.Stat
	0,  // 14: FileResp.Error.type:type_name -> FileResp.Error.Type
	15, // 15: FileResp.Open.error:type_name -> FileResp.Error
	15, // 16: FileResp.Seek.error:type_name -> FileResp.Error
	15, // 17: FileResp.Write.error:type_name -> FileResp.Error
	15, // 18: FileResp.Read.error:type_name -> FileResp.Error
	15, // 19: FileResp.Close.error:type_name -> FileResp.Error
	7,  // 20: FileResp.ReadDir.files:type_name -> StatResp
	15, // 21: FileResp.ReadDir.error:type_name -> FileResp.Error
	7,  // 22: FileResp.Stat.file:type_name -> StatResp
	15, // 23: FileResp.Stat.error:type_name -> FileResp.Error
	1,  // 24: Dfs.File:input_type -> FileReq
	3,  // 25: Dfs.MkDir:input_type -> MkDirReq
	4,  // 26: Dfs.RemoveAll:input_type -> RemoveAllReq
	5,  // 27: Dfs.Rename:input_type -> RenameReq
	6,  // 28: Dfs.Stat:input_type -> StatReq
	2,  // 29: Dfs.File:output_type -> FileResp
	23, // 30: Dfs.MkDir:output_type -> google.protobuf.Empty
	23, // 31: Dfs.RemoveAll:output_type -> google.protobuf.Empty
	23, // 32: Dfs.Rename:output_type -> google.protobuf.Empty
	7,  // 33: Dfs.Stat:output_type -> StatResp
	29, // [29:34] is the sub-list for method output_type
	24, // [24:29] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_dfs_proto_init() }
func file_dfs_proto_init() {
	if File_dfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MkDirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_Open); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_Seek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_Write); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_Close); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_ReadDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq_Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Open); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Seek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Write); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Close); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_ReadDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dfs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResp_Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dfs_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*FileReq_Open_)(nil),
		(*FileReq_Seek_)(nil),
		(*FileReq_Write_)(nil),
		(*FileReq_Read_)(nil),
		(*FileReq_Close_)(nil),
		(*FileReq_ReadDir_)(nil),
		(*FileReq_Stat_)(nil),
	}
	file_dfs_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*FileResp_Open_)(nil),
		(*FileResp_Seek_)(nil),
		(*FileResp_Write_)(nil),
		(*FileResp_Read_)(nil),
		(*FileResp_Close_)(nil),
		(*FileResp_ReadDir_)(nil),
		(*FileResp_Stat_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dfs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dfs_proto_goTypes,
		DependencyIndexes: file_dfs_proto_depIdxs,
		EnumInfos:         file_dfs_proto_enumTypes,
		MessageInfos:      file_dfs_proto_msgTypes,
	}.Build()
	File_dfs_proto = out.File
	file_dfs_proto_rawDesc = nil
	file_dfs_proto_goTypes = nil
	file_dfs_proto_depIdxs = nil
}
